apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ditos-gauchescos-app
  labels:
    app: ditos-gauchescos
    tier: app
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: ditos-gauchescos-app
      labels:
        app: ditos-gauchescos
        tier: app
    spec:
      containers:
      - name: ditos-gauchescos
        image: "ctadeu/ditos:1.3"
        ports:
        - containerPort: 8080

